# Generated by Django 2.1 on 2019-01-30 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='position',
        ),
    ]
