# Generated by Django 2.1 on 2019-01-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0002_remove_candidate_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='position',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
